import { NextPage } from "next";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import { Button, Input, InputLabel } from "@mui/material";
import { ChangeEvent, Dispatch, FormEventHandler, SetStateAction, useState } from "react";
import axios from 'axios';

const Login: NextPage = () => {
    const [name, setName] = useState("my_room");

    const handleChange =
    (setter: Dispatch<SetStateAction<string>>) =>
    async (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      setter(event.target.value);
    };

    const createUser: FormEventHandler<HTMLFormElement> = async (event) => {
        event.preventDefault();
        const response = await axios.post("http://localhost:9000/user", { name })
        console.log(response);
      };

    return (
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a>This Shit</a>
          </h1>
          <form className={styles.description} onSubmit={createUser}>
          <Input
            id="component-simple"
            value={name}
            onChange={handleChange(setName)}
            className={styles.code}
          />
          <Button variant="outlined" type="submit">
            <b>Create Room</b>
          </Button>
        </form>
          </main>
          </div>
    )
}

export default Login;