import "../styles/globals.css";
import type { AppProps } from "next/app";
import { SocketContext, socket } from "../context/socket";
import Head from "next/head";
import Layout from "../components/layout";
import { UserProvider } from "../context/userProvider";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Semanteilay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SocketContext.Provider value={socket}>
        <UserProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
        </UserProvider>
      </SocketContext.Provider>
    </>
  );
}

export default MyApp;
